packages:
  - turbocat-agent
  - backend

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
